### ISSUE TITLE
Updating docs file structure 📁

### ISSUE THREAD

**Issue by brukh** [brukh/hedron-wiki#1]
**Overview.md**
- Describes grid system including breakpoints and container / box abstraction.
- Installation instructions

**Components Directory** 
- LayoutProvider.md
- Section.md
- Container.md
- Box.md
- Hidden.md

**Example Layouts / Usage Directory** 
- Sidebar
- Vertically centered example
- Nesting Example
- Hidden component usage

Useful examples / patterns here:
https://flexbox.webflow.com/

**Comment by ariamckinley** [comment]
Yeah I think this is a solid idea to improve the general usability of the docs.

**Comment by brukh** [comment]
Great, I'll start migrate over what we currently have!
